### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by baielvegas** [baielvegas/TechFestINAI#15]
@mammamoo please 

1.сreate a glossary(dictionary) of terms: give the client and the team a clear understanding of the meaning of words in the context of the website or SRS.

2.describe the website - Tech and Science Fest: give the client and the team an idea of the site

3.describe the role system: show the client and team what roles the users have and in what scenario they can use the site

4.write functional requirements: show the team how the product should work and what features or characteristics it should have

**Comment by mammamoo** [comment]
it's all in the documentation, that you can find in the section Wiki
